### ISSUE TITLE
Change description to fix potentially offensive typo

### ISSUE THREAD

**Issue by pburkholder** [peterabbott/vault-cli#2]
The current GitHub repository description includes slang for female anatomy. Change to `cli`.

-Peter

**Comment by peterabbott** [comment]
Done. Not sure how I missed that.

**Comment by pburkholder** [comment]
Yeah, of the 26 letters available for a typo, it had to be 't' :/

On Mon, Jun 29, 2015 at 3:22 PM, Peter Abbott notifications@github.com
wrote:

> Done. Not sure how I missed that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/peterabbott/vault-cli/issues/2#issuecomment-116803346
> .

## 

_Peter Burkholder_ — Customer Success Engineer

Unavailability: June 22-26 - Team Offsite

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
http://www.linkedin.com/in/pburkholder  Twitter
http://www.twitter.com/pburkholder  Cal
https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK
endar

_CHEF_

CHEF.IO http://www.chef.io/

TM

_chef.io_ http://www.chef.io/   Blog http://www.chef.io/blog/   Facebook
https://www.facebook.com/getchefdotcom   Twitter
https://twitter.com/chef   Youtube https://www.youtube.com/getchef
